try {
    console.log(naoExisto)
} catch (e) {
    console.log('Hove um erro:', e)
}